### ISSUE TITLE
Rename Breaks If Player has / in their name

### ISSUE THREAD

**Issue by Skwidder** [acarapetis/shroudstone#11]
Played against a player named "Nintyo (It/She)", replay name cant have a / in it for clear reasons. error is:

Error renaming /home/skwidder/.steam/root/steamapps/compatdata/2012510/pfx/dosdevices/c:/users/steamuser/AppData/Local/Stormgate/Saved/Replays/257d5054-59f0-4e12-a4a1-0c3f593d1810/CL69129-2024.08.10-05.40.SGReplay => She) - TitansCausewayV2.SGReplay: [Errno 2] No such file or directory: '/home/skwidder/.steam/root/steamapps/compatdata/2012510/pfx/dosdevices/c:/users/steamuser/AppData/Local/Stormgate/Saved/Replays/257d5054-59f0-4e12-a4a1-0c3f593d1810/CL69129-2024.08.10-05.40.SGReplay' -> '/home/skwidder/.steam/root/steamapps/compatdata/2012510/pfx/dosdevices/c:/users/steamuser/AppData/Local/Stormgate/Saved/Replays/257d5054-59f0-4e12-a4a1-0c3f593d1810/2024-08-10 10.40 W 17m34s Dontdiehard IvI Nintyo (It/She) - TitansCausewayV2.SGReplay'

I imagine this would be an issue other forbidden characters if you were on windows. 

Seems like a easy fix but not sure what to replace forbidden characters with. 

Replay attached for your viewing pleasure 

[CL69129-2024.08.10-05.40.SGReplay.zip](https://github.com/user-attachments/files/16568667/CL69129-2024.08.10-05.40.SGReplay.zip)

**Comment by acarapetis** [comment]
Thanks for the report, fixed release will be out soon :)
