### ISSUE TITLE
New Coop Map Support

### ISSUE THREAD

**Issue by Skwidder** [acarapetis/shroudstone#3]
New Coop map TheAbyssalGates (public announcement [here](https://stormgatehub.com/next-stormgate-beta-phase-april-30-new-content-revealed/) Not supported in current code.

Long term a better way to parse the amount of real players is probably needed.

**Comment by acarapetis** [comment]
> Long term a better way to parse the amount of real players is probably needed.

Yeah, it'd be nice. Sadly this kind of map metadata isn't included in replay files, so right now the only way to do it would be to dig through the game assets - not worth it. The current approach should work until user-made maps are available; and at that point I'm hoping we'll get access to some kind of API to query map metadata.
