### ISSUE TITLE
Co-op players not getting set up

### ISSUE THREAD

**Issue by Skwidder** [acarapetis/shroudstone#7]
Co-op players are not getting added at the "start" of the game, so when a player disconnects the renaming fails as its trying to access self.clients[client_id].left_game_time = timestamp with no values for client_id

This seems to be happening on all co-op matches. I will continue to try to find the issue, but have made no progress so far

attached are 2 examples:
[CL68360-2024.07.30-1.zip](https://github.com/user-attachments/files/16435654/CL68360-2024.07.30-1.zip)

**Comment by acarapetis** [comment]
Thanks for the examples, I'll take a look

**Comment by acarapetis** [comment]
Looks like they've made some changes to the protobuf schema in the new patch, and the `Player` record we were previously relying on to link `client_id` to the player UUID is no longer guaranteed to be present.

It looks like maybe we can instead obtain this information from the records that are sent just after the StartGame record:

```
2: 64 # client_id (64 is server)
3: {1: {17: {}}} # StartGame

1: 374
2: 64
3: {
  1: {
    4: {
      1: 1 # client_id?
      2: { # player uuid
        1: -8049995404444220148 
        2: -9097166728186911795 
      }
      3: 127
    }
  }
}

1: 374
2: 1
3: {1: {45: {}}}

1: 436
2: 64
3: {
  1: {
    4: {
      1: 2
      2: {
        1: 2701403674708561426
        2: -6583967714019305456
      }
      3: 129
    }
  }
}

1: 436
2: 2
3: {1: {45: {}}}

1: 884
2: 64
3: {
  1: {
    4: {
      1: 3
      2: {
        1: -8474428718000157415
        2: -8510194396946426951
      }
      3: 130
    }
  }
}

1: 884
2: 3
3: {1: {45: {}}}
```
This looks to me like the server initializing each player (with the key `3.1.4.1` being the client_id), and some kind of ack back from the corresponding client. It would be nice to confirm this - could you please let me know which player it was that disconnected in each of the two examples you provided?

**Comment by Skwidder** [comment]
Player Luso disconnected first from CL68360-2024.07.30-12.50 at around 7:58 in the game. At least in the replay he takes up the first slot. I don't know how to find his player ID(he would have a faction id of 301 if that helps)

In CL68360-2024.07.30-16.19 we won the match so its a bit hard to tell but I believe I (Dontdiehard) left first at the end of the replay.

The only same ID between the 2 games would be mine(Dontdiehard)

Attached is another game with Luso and I, Luso crashes once again at around 8:35

[CL68360-2024.07.30-20.40.SGReplay.zip](https://github.com/user-attachments/files/16444451/CL68360-2024.07.30-20.40.SGReplay.zip)

I wonder what the ack could mean

**Comment by acarapetis** [comment]
Thanks for the info. I updated the parser using my hypothesis regarding the 3.1.4 records, and that seems reasonable; but it's only seeing you disconnecting at the end, not Luso disconnecting. I *think* this message is the server telling us that Luso disconnected:

```
1: 504017
2: 64
3: {
  1: {
    31: {
      1: 1
      2: 3
      3: {
        1: -8049995404444220148
        2: -9097166728186911795
      }
    }
  }
}
```

That's Luso's uuid, and the timestamp matches 7:58. Not sure on the meaning of the other fields, but I'll try treating this as a disconnect for now.

I haven't played any games on the new patch yet so don't have much test data - maybe we need to start a charity data drive in the discord to collect replays with notes about game results + disconnect times :)

**Comment by acarapetis** [comment]
I've published a pre-release using my guesses above: https://github.com/acarapetis/shroudstone/releases/tag/v0.2.0rc2 (or pull the support-coop-68360 branch)

Would be nice to try it out on some more replays, will probably just publish it as v0.2.0 soon anyway though since the old one is straight-up broken.

**Comment by Skwidder** [comment]
22/22 replays renamed successfully most are coop. One "issue" there is more than 1 hero with the first letter of A now... So might need to think about shortening them to something different. got to love coop

**Comment by acarapetis** [comment]
Awesome. I'm going to consider this one fixed, can open a new issue if we encounter any more problems :)
